# Server
url: http://www.chilblane.com
baseurl: ""
source: 'src/pages'
destination: 'dist'
exclude: [CNAME]
keep_files: [assets, CNAME]

# Page meta
title: Daniel Singer | Front-End Developer & UX Designer
description: Personal website of Daniel Singer.
twitter: chilblane
authors: Daniel Singer
