# Server
url: http://www.chilblane.com
baseurl: ""
destination: 'dist'
exclude: [assets, node_modules, src, CNAME, Gemfile, Gemfile.lock, Gruntfile.js, package.json, README.md]
keep_files: [assets]

# Page meta
title: Daniel Singer | Front-End Developer & UX Designer
description: Personal website of Daniel Singer.
twitter: chilblane
authors: Daniel Singer
