# Server
url: http://www.chilblane.com
baseurl: ""
exclude: [assets]

# Page meta
title: Daniel Singer | Front-End Developer & UX Designer
description: Personal website of Daniel Singer.
twitter: chilblane
authors: Daniel Singer
