# Server
url: http://www.chilblane.com
baseurl: ""
exclude: [node_modules, src, CNAME, Gemfile, Gemfile.lock, Gruntfile.js, package.json, README.md]
permalink: /:title

# Page meta
title: Daniel Singer
description: Personal website of Daniel Singer, front-end developer & UX designer. Not a paid actor.
twitter: chilblane
authors: Daniel Singer
